
hide footbox

participant "Controler" as ctrl
participant "Joueur" as user

alt Si le joueur veut lancer une attaque
    
    ctrl -> user++ : demanderTerritoireSource()
    return
    ctrl -> ctrl: choisirTerritoireSource()
    ctrl -> user++ : demanderTerritoireCiblePourAttaquer(attaquant,tS)
    return
    ctrl -> ctrl: choisirTerrioireCible()
    ctrl -> user++ : demanderNbDesAttaque(tS)()
    return
    ctrl -> ctrl: choisirNbDesAttaque()
    ctrl -> user++ :lancerDes(desAttaque)
    return
    user -> ctrl : List<Dé> attaquant et défenseur 
    return
    ctrl -> user++ : resolveAttack(resultatsAttaque, desAttaque)
    return


    alt si l'attaquant à réussi l'attaque

        ctrl -> user++ :demanderNbRegimentDeplace(tS, tC)
        return
        ctrl -> ctrl:choisrNbRegimentDeplace()
    end
end
