
hide footbox

participant "Controler" as ctrl
actor "Joueur" as user

alt Si le joueur veut attaquer
    loop Tant que le joueur peut mener une attaque
        ctrl -> user ++: obtenirTerritoires()
        return List<Territoire>

        ctrl -> ctrl : choisirTerritoirePourAttaque()
        note right
            Afficher une liste de 
            proposition des territoires pour lancer l'attaque
            et saisir le choix d'utilisateur
        end note

        ctrl -> user ++: getTerritoire(int)
        return Territoire

        ctrl -> ctrl : choisirNbDés()
        note right
            Demander à l'utilisateur le nombre de dés
        end note

        ctrl -> user++ : lancerDés(int)
        return List<Dé>

        ctrl -> ctrl : Lancer les dés de la défense adverse
        note right
            Il faudra penser à obtenir le nombre de 
            dés que le joueur adverse peut jeter
        end note

        ctrl -> ctrl : Déterminer les troupes restantes
        note left
            /!\ Attention, la détermination de la victoire 
            entre deux dés n'est pas faite
        end note

        alt L'attaquant a réussi l'attaque
            ctrl -> ctrl : retirerTerritoireAdversaire()
            note right
                Retire le territoire du défenseur
            end note

            ctrl -> user ++: ajouterTerritoire(Territoire)
            return

            ctrl -> ctrl : choisirNombreTroupesDeplacement()
            note right
                Demander la saisie du nombre 
                de troupes à déplacer
            end note
            ctrl -> user ++: deplacerRegiment(\n\tTerritoireSource, \n\tTerritoireCible, \n\tnombreRégiments)
            return

        end
    end
end