
hide footbox

participant "Controler" as ctrl
participant "Joueur" as user

ctrl -> user ++: calculerNbRenforts()
return nbRenforts

alt Si le joueur a au moins 3 cartes
    ctrl -> user ++: echangerCartes()
    return nbRenfortsCartes
end

loop Pour chaque nouveau régiment à ajouter
    ctrl -> user ++: getArmee()\n\t.ajouterPion(pion)
    return
end
ctrl -> user ++: getPionsAPlacer()
return List<Pion>
ctrl -> user ++: obtenirTerritoire()
return List<Territoire>
ctrl -> user ++: obtenirTerritoire()\n\t.ajouterRegiment(Pion, 1)
return
