title Déroulement d'un tour

hide footbox
participant "Joueur" as user
participant "Controler" as ctrl

activate ctrl
== Phase renfort ==

!include renfort.puml

== Phase attaque ==

!include attaque.puml

== Phase fortification ==

!include fortification.puml
deactivate ctrl
