
!includeurl https://raw.githubusercontent.com/manuvai/plantuml-utils/master/class_diagram_utils.puml
skinparam groupInheritance 1

hide <<Legend>> circle
hide <<Legend>> stereotype

class Légende<<Legend>> {
    - - private\t\tattribute
    # # protected\tattribute
    + + public\t\tattribute
    - - private\t\tmethod()
    # # protected\tmethod()
    + + public\t\tmethod()
}
