
!if (%not($included == %true()))
    !include lib.iuml

    !$included = %true()
!endif

<style>

.Yifan {
    BackgroundColor LightBlue
}

.Han {
    BackgroundColor LightGreen
}

.Gauthier {
    BackgroundColor LightYellow
}

.Fatima {
    BackgroundColor LightPink
}

.Manu {
    BackgroundColor LightGray
}

</style>

package model {
    class "CarteRisk" as Carte <<Yifan>> {
        -member(TypePion, typePion)
        -member(Territoire, territoire)
    }

    class Dé <<Manu>> {
        -int(valeur)
        +int("recupererValeur()")
        +void("lancerDé()")
    }

    class Plateau <<Model>> <<Han>> {
        -list(Continent, continents)
        -list(Joueur, joueurs)
        -member("Map<CarteRisk, Integer>", cartes)
        +void("distribuerCartes()")
        +void("initialiserParties()")
        +list(Joueur, "getJoueurs()")
        +member("Map<CarteRisk, Integer>", "getCartes()")
        +void("enleverJoueur(Joueur)")
    }

    class Continent <<Han>> {
        -string(nom)
        -int(bonusRenforts)
        -list(Territoire, territoires)
        +list(Territoire, "getTerritoires()")
        +int("getBonusTerritoires()")
    }

    class Territoire <<Fatima>> {
        -string(nom)
        -member("Déploiement", "unitésDéployées")
        +string("getNom()")
        +list(Territoire, "getVoisins()")
        +boolean("estVoisin(Territoire)")
        +member(Joueur, "getPropriétaire()")
        +void("ajouterRégiment(Pion, int)")
        +void("retirerRégiment(Pion, int)")
    }

    class Joueur <<Manu>> {
        -string(nom)
        -string(prenom) 
        -member("Map<CarteRisk, Integer>", cartes)
        +list("Dé", "lancerDés(int)")
        +int("calculerNbRenforts()")
        +list(Territoire, "obtenirTerritoires()")
        +void("ajouterCarte(CarteRisk)")
        +void("échangerCartes(List<CarteRisk>)")
        +void("attaquer(Territoire, Territoire, int)")
        +void("deplacerTroupes(Territoire, Territoire, int)")
    }

    class Armée <<Manu>> {
        -string(couleur)
        -list(Pion, pions)
    }

    class Pion <<Gauthier>> {
        -string(nomPion)
        -member(TypePion, typePion)
        +int("obtenirNbRégiment()")
    }

    ' note over Pion
    '     Le calcul du Nb de régiment sera fait
    ' end note

    enum TypePion <<Gauthier>> {
        INFANTERIE
        CAVALERIE
        ARTILLERIE
    }

    class Déploiement <<Fatima>> {
        -int("qtéDéployée")
        -member(Pion, "pionRattaché")
        +void("ajouterQuantité(int)")
        +void("retirerQuantité(int)")
    }

    class Joker <<Yifan>> {

    }
    
    ' Infanterie .[#hidden]. Cavalerie
    ' Cavalerie .[#hidden]. Artillerie

    Plateau *-- "0..6" Continent
    Continent *-r- "0..*" Territoire

    Joueur *-l- "1..1" Armée : arméePossédée
    Joueur -- "0..*" Carte
    Joueur -- "0..*" Territoire

    Armée o-d- Pion

    Pion "0..*" -r- "1..1" TypePion : typeDePion

    ' Infanterie -r-|> Pion
    ' Cavalerie -r-|> Pion
    ' Artillerie -r-|> Pion

    Joueur "0..5" --o Plateau
    Carte "0..30" --o Plateau

    Joker -l-|> Carte


    Carte "0..*" o-l- "1..1" TypePion : typeLié
    Carte o-- "1..1" Territoire : territoireLié
    Territoire -d- Territoire #Green: <color:Green>territoiresVoisins

    (Pion, Territoire) . Déploiement
}
