@startuml

hide footbox
actor "Joueur" as user

participant "Systeme" as app

activate app 
    loop Pour chaque joueur de la partie
        app -> user ++ : init()
        return
        app -> app : ajouterJoueur(Joueur)

    end

    ' ref over app, user
    '     Initialiser les territoires des joueurs
    ' end ref
    !include inc/initialisation_territoires.puml
    
    loop Tant qu'il n'y a pas de vainqueur
        !include inc/tour.puml
    end


deactivate app 

@enduml

